<RockSimDocument>
    <FileVersion>4</FileVersion>
    <DesignInformation>
        <RocketDesign>
            <Name>Patriot</Name>
            <StageCount>1</StageCount>
            <DisplayFlags>7</DisplayFlags>
            <ViewType>0</ViewType>
            <ViewStageCount>3</ViewStageCount>
            <ViewTypeEdit>0</ViewTypeEdit>
            <ViewStageCountEdit>3</ViewStageCountEdit>
            <ZoomFactor>0.0</ZoomFactor>
            <ZoomFactorEdit>0.0</ZoomFactorEdit>
            <ScrollPosX>0</ScrollPosX>
            <ScrollPosY>0</ScrollPosY>
            <ScrollPosXEdit>0</ScrollPosXEdit>
            <ScrollPosYEdit>0</ScrollPosYEdit>
            <ThreeDFlags>0</ThreeDFlags>
            <ThreeDFlagsEdit>0</ThreeDFlagsEdit>
            <LastSerialNumber>15</LastSerialNumber>
            <Stage3Mass>0.0</Stage3Mass>
            <Stage2Mass>0.0</Stage2Mass>
            <Stage1Mass>0.0</Stage1Mass>
            <Stage3CG>299.9738269092911</Stage3CG>
            <Stage2CGAlone>0.0</Stage2CGAlone>
            <Stage1CGAlone>0.0</Stage1CGAlone>
            <Stage321CG>0.0</Stage321CG>
            <Stage32CG>0.0</Stage32CG>
            <CPCalcFlags>1</CPCalcFlags>
            <CPSimFlags>1</CPSimFlags>
            <UseKnownMass>0</UseKnownMass>
            <Stage3Parts>
                <NoseCone>
                    <KnownMass>11.056</KnownMass>
                    <Density>680.0</Density>
                    <Material>Cardboard</Material>
                    <Name>Nose cone</Name>
                    <KnownCG>41.275</KnownCG>
                    <UseKnownCG>1</UseKnownCG>
                    <Xb>0.0</Xb>
                    <CalcMass>11.141055677705575</CalcMass>
                    <CalcCG>41.275</CalcCG>
                    <DensityType>0</DensityType>
                    <RadialLoc>0.0</RadialLoc>
                    <RadialAngle>0.0</RadialAngle>
                    <LocationMode>0</LocationMode>
                    <Len>120.0</Len>
                    <FinishCode>1</FinishCode>
                    <SerialNo>0</SerialNo>
                    <ShapeCode>1</ShapeCode>
                    <ConstructionType>1</ConstructionType>
                    <WallThickness>1.1800000000000004</WallThickness>
                    <ShapeParameter>0.0</ShapeParameter>
                    <AttachedParts/>
                    <BaseDia>41.58</BaseDia>
                    <ShoulderLen>30.0</ShoulderLen>
                    <ShoulderOD>40.5</ShoulderOD>
                </NoseCone>
                <BodyTube>
                    <KnownMass>4.097100268029339</KnownMass>
                    <Density>680.0</Density>
                    <Material>Cardboard</Material>
                    <Name>Body tube</Name>
                    <KnownCG>0.0</KnownCG>
                    <UseKnownCG>0</UseKnownCG>
                    <Xb>0.0</Xb>
                    <CalcMass>4.097100268029339</CalcMass>
                    <CalcCG>39.0</CalcCG>
                    <DensityType>0</DensityType>
                    <RadialLoc>0.0</RadialLoc>
                    <RadialAngle>0.0</RadialAngle>
                    <LocationMode>0</LocationMode>
                    <Len>78.0</Len>
                    <FinishCode>1</FinishCode>
                    <SerialNo>1</SerialNo>
                    <OD>41.58</OD>
                    <ID>40.38</ID>
                    <IsMotorMount>0</IsMotorMount>
                    <MotorDia>40.38</MotorDia>
                    <EngineOverhang>0.0</EngineOverhang>
                    <IsInsideTube>0</IsInsideTube>
                    <AttachedParts>
                        <Ring>
                            <KnownMass>2.6665797779680225</KnownMass>
                            <Density>680.0</Density>
                            <Material>Cardboard</Material>
                            <Name>Tube coupler</Name>
                            <KnownCG>0.0</KnownCG>
                            <UseKnownCG>0</UseKnownCG>
                            <Xb>-19.1</Xb>
                            <CalcMass>2.6665797779680225</CalcMass>
                            <CalcCG>19.05</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>2</LocationMode>
                            <Len>38.1</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>2</SerialNo>
                            <OD>40.513</OD>
                            <ID>38.862</ID>
                            <UsageCode>4</UsageCode>
                            <AutoSize>0</AutoSize>
                        </Ring>
                        <MassObject>
                            <KnownMass>1.0045</KnownMass>
                            <Density>0.0</Density>
                            <Material></Material>
                            <Name>Shock Cord</Name>
                            <KnownCG>78.0</KnownCG>
                            <UseKnownCG>1</UseKnownCG>
                            <Xb>78.0</Xb>
                            <CalcMass>0.0</CalcMass>
                            <CalcCG>0.0</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>0</LocationMode>
                            <Len>280.0</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>3</SerialNo>
                            <TypeCode>0</TypeCode>
                        </MassObject>
                        <Parachute>
                            <KnownMass>2.041</KnownMass>
                            <Density>1.11533779017155E-8</Density>
                            <Material>Polyethylene LDPE</Material>
                            <Name>Parachute</Name>
                            <KnownCG>0.0</KnownCG>
                            <UseKnownCG>1</UseKnownCG>
                            <Xb>34.0</Xb>
                            <CalcMass>0.3204081381599999</CalcMass>
                            <CalcCG>0.0</CalcCG>
                            <DensityType>1</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>0</LocationMode>
                            <Len>110.0</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>4</SerialNo>
                            <Dia>304.8</Dia>
                            <ShroudLineCount>6</ShroudLineCount>
                            <Thickness>0.0</Thickness>
                            <ShroudLineLen>300.0</ShroudLineLen>
                            <ChuteCount>1</ChuteCount>
                            <ShroudLineMassPerMM>1.78E-4</ShroudLineMassPerMM>
                            <ShroudLineMaterial>30 Lb. kevlar</ShroudLineMaterial>
                            <DragCoefficient>0.75</DragCoefficient>
                        </Parachute>
                    </AttachedParts>
                </BodyTube>
                <BodyTube>
                    <KnownMass>10.331286782909375</KnownMass>
                    <Density>680.0</Density>
                    <Material>Cardboard</Material>
                    <Name>Body tube</Name>
                    <KnownCG>0.0</KnownCG>
                    <UseKnownCG>0</UseKnownCG>
                    <Xb>0.0</Xb>
                    <CalcMass>10.331286782909375</CalcMass>
                    <CalcCG>84.5</CalcCG>
                    <DensityType>0</DensityType>
                    <RadialLoc>0.0</RadialLoc>
                    <RadialAngle>0.0</RadialAngle>
                    <LocationMode>0</LocationMode>
                    <Len>169.0</Len>
                    <FinishCode>3</FinishCode>
                    <SerialNo>5</SerialNo>
                    <OD>41.58</OD>
                    <ID>40.18</ID>
                    <IsMotorMount>0</IsMotorMount>
                    <MotorDia>40.18</MotorDia>
                    <EngineOverhang>0.0</EngineOverhang>
                    <IsInsideTube>0</IsInsideTube>
                    <AttachedParts>
                        <Ring>
                            <KnownMass>2.6665797779680225</KnownMass>
                            <Density>680.0</Density>
                            <Material>Cardboard</Material>
                            <Name>Tube coupler</Name>
                            <KnownCG>0.0</KnownCG>
                            <UseKnownCG>0</UseKnownCG>
                            <Xb>150.0</Xb>
                            <CalcMass>2.6665797779680225</CalcMass>
                            <CalcCG>19.05</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>0</LocationMode>
                            <Len>38.1</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>6</SerialNo>
                            <OD>40.513</OD>
                            <ID>38.862</ID>
                            <UsageCode>4</UsageCode>
                            <AutoSize>0</AutoSize>
                        </Ring>
                    </AttachedParts>
                </BodyTube>
                <BodyTube>
                    <KnownMass>10.331286782909375</KnownMass>
                    <Density>680.0</Density>
                    <Material>Cardboard</Material>
                    <Name>Body tube</Name>
                    <KnownCG>0.0</KnownCG>
                    <UseKnownCG>0</UseKnownCG>
                    <Xb>0.0</Xb>
                    <CalcMass>10.331286782909375</CalcMass>
                    <CalcCG>84.5</CalcCG>
                    <DensityType>0</DensityType>
                    <RadialLoc>0.0</RadialLoc>
                    <RadialAngle>0.0</RadialAngle>
                    <LocationMode>0</LocationMode>
                    <Len>169.0</Len>
                    <FinishCode>1</FinishCode>
                    <SerialNo>7</SerialNo>
                    <OD>41.58</OD>
                    <ID>40.18</ID>
                    <IsMotorMount>0</IsMotorMount>
                    <MotorDia>40.18</MotorDia>
                    <EngineOverhang>0.0</EngineOverhang>
                    <IsInsideTube>0</IsInsideTube>
                    <AttachedParts>
                        <BodyTube>
                            <KnownMass>1.4943351740687072</KnownMass>
                            <Density>1121.29241</Density>
                            <Material>Paper</Material>
                            <Name>Body tube</Name>
                            <KnownCG>0.0</KnownCG>
                            <UseKnownCG>0</UseKnownCG>
                            <Xb>98.0</Xb>
                            <CalcMass>1.4943351740687072</CalcMass>
                            <CalcCG>35.0</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>0</LocationMode>
                            <Len>70.0</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>8</SerialNo>
                            <OD>18.694</OD>
                            <ID>18.034</ID>
                            <IsMotorMount>1</IsMotorMount>
                            <MotorDia>18.034</MotorDia>
                            <EngineOverhang>5.1</EngineOverhang>
                            <IsInsideTube>1</IsInsideTube>
                            <AttachedParts>
                                <Ring>
                                    <KnownMass>1.6736136674774722</KnownMass>
                                    <Density>1121.29241</Density>
                                    <Material>Paper</Material>
                                    <Name>Ring</Name>
                                    <KnownCG>0.0</KnownCG>
                                    <UseKnownCG>0</UseKnownCG>
                                    <Xb>0.0</Xb>
                                    <CalcMass>1.6736136674774722</CalcMass>
                                    <CalcCG>0.75</CalcCG>
                                    <DensityType>0</DensityType>
                                    <RadialLoc>0.0</RadialLoc>
                                    <RadialAngle>0.0</RadialAngle>
                                    <LocationMode>0</LocationMode>
                                    <Len>1.5</Len>
                                    <FinishCode>0</FinishCode>
                                    <SerialNo>9</SerialNo>
                                    <OD>40.0</OD>
                                    <ID>18.25</ID>
                                    <UsageCode>0</UsageCode>
                                    <AutoSize>0</AutoSize>
                                </Ring>
                                <Ring>
                                    <KnownMass>1.4320655546388907</KnownMass>
                                    <Density>1121.29241</Density>
                                    <Material>Paper</Material>
                                    <Name>Mylar Ring</Name>
                                    <KnownCG>0.0</KnownCG>
                                    <UseKnownCG>0</UseKnownCG>
                                    <Xb>33.5</Xb>
                                    <CalcMass>1.4320655546388907</CalcMass>
                                    <CalcCG>2.5</CalcCG>
                                    <DensityType>0</DensityType>
                                    <RadialLoc>0.0</RadialLoc>
                                    <RadialAngle>0.0</RadialAngle>
                                    <LocationMode>0</LocationMode>
                                    <Len>5.0</Len>
                                    <FinishCode>0</FinishCode>
                                    <SerialNo>10</SerialNo>
                                    <OD>18.034</OD>
                                    <ID>0.0</ID>
                                    <UsageCode>0</UsageCode>
                                    <AutoSize>0</AutoSize>
                                </Ring>
                                <Ring>
                                    <KnownMass>2.510420501216208</KnownMass>
                                    <Density>1121.29241</Density>
                                    <Material>Paper</Material>
                                    <Name>Ring</Name>
                                    <KnownCG>0.0</KnownCG>
                                    <UseKnownCG>0</UseKnownCG>
                                    <Xb>13.0</Xb>
                                    <CalcMass>2.510420501216208</CalcMass>
                                    <CalcCG>1.1250000000000002</CalcCG>
                                    <DensityType>0</DensityType>
                                    <RadialLoc>0.0</RadialLoc>
                                    <RadialAngle>0.0</RadialAngle>
                                    <LocationMode>2</LocationMode>
                                    <Len>2.2500000000000004</Len>
                                    <FinishCode>0</FinishCode>
                                    <SerialNo>11</SerialNo>
                                    <OD>40.0</OD>
                                    <ID>18.25</ID>
                                    <UsageCode>0</UsageCode>
                                    <AutoSize>0</AutoSize>
                                </Ring>
                                <MassObject>
                                    <KnownMass>1.4</KnownMass>
                                    <Density>0.0</Density>
                                    <Material></Material>
                                    <Name>Engine hook</Name>
                                    <KnownCG>8.1</KnownCG>
                                    <UseKnownCG>1</UseKnownCG>
                                    <Xb>8.1</Xb>
                                    <CalcMass>0.0</CalcMass>
                                    <CalcCG>0.0</CalcCG>
                                    <DensityType>0</DensityType>
                                    <RadialLoc>0.0</RadialLoc>
                                    <RadialAngle>0.0</RadialAngle>
                                    <LocationMode>0</LocationMode>
                                    <Len>68.0</Len>
                                    <FinishCode>0</FinishCode>
                                    <SerialNo>12</SerialNo>
                                    <TypeCode>0</TypeCode>
                                </MassObject>
                                <Ring>
                                    <KnownMass>0.228902534221953</KnownMass>
                                    <Density>1121.29241</Density>
                                    <Material>Paper</Material>
                                    <Name>Engine block</Name>
                                    <KnownCG>0.0</KnownCG>
                                    <UseKnownCG>0</UseKnownCG>
                                    <Xb>0.0</Xb>
                                    <CalcMass>0.228902534221953</CalcMass>
                                    <CalcCG>2.5</CalcCG>
                                    <DensityType>0</DensityType>
                                    <RadialLoc>0.0</RadialLoc>
                                    <RadialAngle>0.0</RadialAngle>
                                    <LocationMode>0</LocationMode>
                                    <Len>5.0</Len>
                                    <FinishCode>0</FinishCode>
                                    <SerialNo>13</SerialNo>
                                    <OD>18.034</OD>
                                    <ID>16.53</ID>
                                    <UsageCode>2</UsageCode>
                                    <AutoSize>0</AutoSize>
                                </Ring>
                            </AttachedParts>
                        </BodyTube>
                        <FinSet>
                            <KnownMass>3.136767461586001</KnownMass>
                            <Density>128.147704</Density>
                            <Material>Balsa</Material>
                            <Name>Fin set</Name>
                            <KnownCG>0.0</KnownCG>
                            <UseKnownCG>0</UseKnownCG>
                            <Xb>-0.0</Xb>
                            <CalcMass>3.136767461586001</CalcMass>
                            <CalcCG>46.94186046511627</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>2</LocationMode>
                            <Len>0.0</Len>
                            <FinishCode>1</FinishCode>
                            <SerialNo>14</SerialNo>
                            <FinCount>4</FinCount>
                            <RootChord>75.0</RootChord>
                            <TipChord>32.5</TipChord>
                            <SemiSpan>34.5</SemiSpan>
                            <SweepDistance>43.0</SweepDistance>
                            <Thickness>3.3</Thickness>
                            <ShapeCode>0</ShapeCode>
                            <TipShapeCode>0</TipShapeCode>
                            <TabLength>50.0</TabLength>
                            <TabDepth>0.0</TabDepth>
                            <TabOffset>0.0</TabOffset>
                            <SweepMode>1</SweepMode>
                            <CantAngle>0.0</CantAngle>
                        </FinSet>
                        <LaunchLug>
                            <KnownMass>0.46822631754118493</KnownMass>
                            <Density>1121.29241</Density>
                            <Material>paper</Material>
                            <Name>Launch lug</Name>
                            <KnownCG>0.0</KnownCG>
                            <UseKnownCG>0</UseKnownCG>
                            <Xb>17.0</Xb>
                            <CalcMass>0.46822631754118493</CalcMass>
                            <CalcCG>30.5</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.785398185</RadialAngle>
                            <LocationMode>0</LocationMode>
                            <Len>61.0</Len>
                            <FinishCode>1</FinishCode>
                            <SerialNo>15</SerialNo>
                            <OD>4.8580000000000005</OD>
                            <ID>3.8580000000000005</ID>
                        </LaunchLug>
                    </AttachedParts>
                </BodyTube>
            </Stage3Parts>
            <Stage2Parts/>
            <Stage1Parts/>
        </RocketDesign>
    </DesignInformation>
</RockSimDocument>